apiVersion: v1
kind: Service
metadata:
  name: mail-ui
  labels:
    {{- include "mail.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: ui
      protocol: TCP
      name: ui
  selector:
    {{- include "mail.selectorLabels" . | nindent 4 }} 