apiVersion: v2
name: orocommerce
version: 0.1.0
description: A Helm chart for deploying OroCommerce

dependencies:
  - name: postgresql
    version: 11.x.x
    repository: https://charts.bitnami.com/bitnami
