image:
  repository: oroinc/runtime
  tag: "6.1-latest"
  pullPolicy: IfNotPresent

env:
  ORO_ENV: prod
  ORO_LOG_PATH: php://stderr
  ORO_USER_RUNTIME: www-data

service:
  type: ClusterIP
  port: 9000

phpfpm:
  replicas: 1
  resources:
    limits:
      cpu: "1000m"
      memory: "1Gi"
    requests:
      cpu: "500m"
      memory: "512Mi"
  tmpfs:
    - /tmp 