image:
  repository: oroinc/runtime
  tag: "6.1-latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9000

phpfpm:
  replicas: 1
  resources:
    limits:
      cpu: "1000m"
      memory: "1Gi"
    requests:
      cpu: "500m"
      memory: "512Mi"
  tmpfs:
    - /tmp 
  volumes:
    oroApp:
      claimName: "oro-app-orocommerce"
    cache:
      claimName: "cache-orocommerce"
    maintenance:
      claimName: "maintenance-orocommerce"
    publicStorage:
      claimName: "public-storage-orocommerce"
    privateStorage:
      claimName: "private-storage-orocommerce" 