apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "webserver.fullname" . }}-ingress
spec:
  rules:
    - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "webserver.fullname" . }}
              port:
                number: {{ .Values.service.port }}
