apiVersion: v1
kind: Service
metadata:
  name: {{ include "webserver.fullname" . }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ include "webserver.name" . }}
